### ISSUE TITLE
what are you planning?

### ISSUE THREAD

**Issue by Harkirat155** [adesgautam/Fedlearn#1]
as to would you like to get back the raw gradients to main_server after training from each device, or you wish to aggregate the model at some trusted device and get back the aggregated result?

**Comment by Harkirat155** [comment]
> as to would you like to get back the raw gradients to main_server after training from each device, or you wish to aggregate the model at some trusted device and get back the aggregated result?

according to current working, you are getting back the raw the gradients, but instead sending raw gradients to another trusted device could be thought off possibly being a better approach.

**Comment by adesgautam** [comment]
Yes, I want to add a secure aggregator, where the gradients would be sent and after aggregation it will be sent to the main server. Also, I am planning to integrate additive secret sharing so that the secure aggregator doesn't peep into the gradients.
